import React from "react";

// The four labels every number in the lab carries. The visual encoding is not
// decorative: the left border is solid for something this session computed,
// and dotted for something merely quoted from a paper. A learner scanning the
// page can see the difference without reading the words.
export const EVIDENCE = {
  "Live computation": {
    className: "badge live",
    meaning:
      "Computed while you watch, in your browser, from the graph on screen. " +
      "The browser engine is checked against the Python pipeline by " +
      "Backend/tests/test_js_parity.py.",
  },
  "Synthetic data": {
    className: "badge synthetic",
    meaning:
      "Generated by a seeded random process rather than measured from the " +
      "world. Reproducible from the seed.",
  },
  "Precomputed result": {
    className: "badge precomputed",
    meaning:
      "Measured earlier by this project from frozen checkpoints, then shipped " +
      "as a data file. Not recomputed as you browse.",
  },
  "Paper-reported result": {
    className: "badge paper",
    meaning:
      "Taken from a published source. Not measured by this project and not " +
      "independently verified here.",
  },
};

export function EvidenceBadge({ type, title }) {
  const entry = EVIDENCE[type];

  if (!entry) return <span className="badge other">{type || "Unlabelled"}</span>;

  return (
    <span className={entry.className} title={title || entry.meaning}>
      {type}
    </span>
  );
}

/**
 * Provenance travels with the number rather than living in a caption
 * elsewhere on the page.
 */
export function EvidenceNote({ evidence, extra }) {
  if (!evidence) return null;

  return (
    <div className="evidence-note">
      <EvidenceBadge type={evidence.evidenceType} />
      <span>{evidence.source}</span>
      {extra && <span>{extra}</span>}
    </div>
  );
}
